# Skiller Release Workflow
# 将此文件放置到 zanwei/skiller 仓库的 .github/workflows/ 目录下
#
# 功能：
# 1. 当创建新的 Git tag (如 v1.0.5) 时自动触发
# 2. 在 macOS、Windows、Linux 上构建 Tauri 应用
# 3. 创建带版本号和不带版本号的安装包（用于固定下载链接）
# 4. 发布到 GitHub Releases

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}
      release_upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Skiller ${{ github.ref_name }}
          draft: true
          prerelease: false

  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS Apple Silicon (M1/M2/M3)
          - platform: macos-latest
            target: aarch64-apple-darwin
            artifact_name: Skiller_aarch64.dmg
            artifact_pattern: "*.dmg"
          # macOS Intel
          - platform: macos-latest
            target: x86_64-apple-darwin
            artifact_name: Skiller_x64.dmg
            artifact_pattern: "*.dmg"
          # Windows
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: Skiller_x64-setup.exe
            artifact_pattern: "*.exe"
          # Linux
          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            artifact_name: Skiller_amd64.deb
            artifact_pattern: "*.deb"

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-action@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install frontend dependencies
        run: npm ci

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          args: --target ${{ matrix.target }}

      - name: Find and rename artifact (create version-less copy)
        shell: bash
        run: |
          # 查找构建产物
          if [ "${{ matrix.platform }}" == "windows-latest" ]; then
            ARTIFACT=$(find src-tauri/target/${{ matrix.target }}/release/bundle -name "${{ matrix.artifact_pattern }}" -type f | head -1)
          elif [ "${{ matrix.platform }}" == "macos-latest" ]; then
            ARTIFACT=$(find src-tauri/target/${{ matrix.target }}/release/bundle/dmg -name "${{ matrix.artifact_pattern }}" -type f | head -1)
          else
            ARTIFACT=$(find src-tauri/target/${{ matrix.target }}/release/bundle/deb -name "${{ matrix.artifact_pattern }}" -type f | head -1)
          fi
          
          echo "Found artifact: $ARTIFACT"
          
          # 创建不带版本号的副本
          ARTIFACT_DIR=$(dirname "$ARTIFACT")
          cp "$ARTIFACT" "$ARTIFACT_DIR/${{ matrix.artifact_name }}"
          
          echo "ARTIFACT_PATH=$ARTIFACT_DIR/${{ matrix.artifact_name }}" >> $GITHUB_ENV

      - name: Upload version-less artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_upload_url }}
          asset_path: ${{ env.ARTIFACT_PATH }}
          asset_name: ${{ matrix.artifact_name }}
          asset_content_type: application/octet-stream

  publish-release:
    needs: [create-release, build-tauri]
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release
        uses: actions/github-script@v7
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
